-- Xóa database cũ nếu tồn tại để tránh lỗi
DROP DATABASE IF EXISTS FILEBENH;

-- Tạo lại database với bảng mã chuẩn
CREATE DATABASE FILEBENH CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE FILEBENH;


--
-- Bảng TenTrieuChung ĐÃ SỬA LỖI
-- -> Thêm cột ID làm khóa chính để định danh
--
CREATE TABLE TenTrieuChung (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TrieuChung NVARCHAR(500) NOT NULL
);

--
-- Bảng DuaLoiKhuyen ĐÃ SỬA LỖI
-- -> Thêm cột TrieuChung_ID để liên kết với bảng TenTrieuChung
--
CREATE TABLE DuaLoiKhuyen (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  TrieuChung_ID INT NOT NULL,
  ChuanDoan NVARCHAR(500) NOT NULL,
  LoiKhuyen NVARCHAR(500) NOT NULL,
  FOREIGN KEY (TrieuChung_ID) REFERENCES TenTrieuChung(ID)
);


INSERT INTO TenTrieuChung(ID, TrieuChung) VALUES (1, 'ho, đau họng');
INSERT INTO DuaLoiKhuyen(TrieuChung_ID, ChuanDoan, LoiKhuyen) VALUES (1, 'Có thể bạn đang bị cảm cúm', 'Ban nên nghỉ ngơi nhiều hơn');

INSERT INTO TenTrieuChung(ID, TrieuChung) VALUES (2, 'sốt, phát ban');
INSERT INTO DuaLoiKhuyen(TrieuChung_ID, ChuanDoan, LoiKhuyen) VALUES (2, 'Nghi ngờ sốt phát ban', 'Cần theo dõi nhiệt độ và đi khám nếu sốt cao không hạ.');

INSERT INTO TenTrieuChung(ID, TrieuChung) VALUES (3, 'ho, sốt, khó thở');
INSERT INTO DuaLoiKhuyen(TrieuChung_ID, ChuanDoan, LoiKhuyen) VALUES (3, 'Nghi ngờ Viêm phế quản', 'Giữ ấm, uống thuốc long đờm và đi khám bác sĩ.');

INSERT INTO TenTrieuChung(ID, TrieuChung) VALUES 
(4, 'sốt cao, ho có đờm, đau ngực khi thở'),
(5, 'sốt cao, đau đầu, đau sau hốc mắt, phát ban'),
(6, 'mắt đỏ, chảy nước mắt, ngứa mắt, có ghèn'),
(7, 'đau bụng, nôn mửa, tiêu chảy'),
(8, 'ợ chua, nóng rát cổ họng, đau ngực'),
(9, 'đau đầu, nghẹt mũi, chảy nước mũi'),
(10, 'đau vùng thắt lưng, tiểu buốt, tiểu ra máu'),
(11, 'tiểu buốt, tiểu rắt, nước tiểu đục'),
(12, 'đau đầu dữ dội một bên, buồn nôn, sợ ánh sáng'),
(13, 'sốt, mệt mỏi, vàng da, vàng mắt'),
(14, 'khát nước nhiều, đi tiểu nhiều, sụt cân nhanh'),
(15, 'ngứa, nổi mẩn đỏ, da khô, bong tróc'),
(16, 'đau khớp, sưng khớp, cứng khớp vào buổi sáng'),
(17, 'đau rát một vùng da, nổi mụn nước thành dải'),
(18, 'sốt cao, đau mỏi toàn thân, nhức đầu, mệt mỏi'),
(19, 'chóng mặt, nhức đầu vùng gáy, hoa mắt'),
(20, 'khó thở khò khè, ho về đêm, nặng ngực'),
(21, 'đau tai, sốt, chảy mủ tai, nghe kém'),
(22, 'hắt hơi, sổ mũi, ngứa mắt, nổi mề đay'),
(23, 'đau rát hậu môn, đi cầu ra máu tươi, sa búi trĩ'),
(24, 'đau bụng hố chậu phải, sốt, buồn nôn'),
(25, 'khó vào giấc, ngủ không sâu, thức dậy sớm'),
(26, 'buồn bã kéo dài, mất hứng thú, mệt mỏi, rối loạn ăn ngủ'),
(27, 'đau thượng vị, ợ hơi, buồn nôn, ăn không tiêu'),
(28, 'sưng, nóng, đỏ, đau dữ dội ở khớp ngón chân cái'),
(29, 'đau lưng, đau lan xuống chân, tê bì chân'),
(30, 'chóng mặt, buồn nôn, mất thăng bằng, ù tai'),
(31, 'hắt hơi, sổ mũi, nghẹt mũi, ho nhẹ, không sốt'),
(32, 'da đỏ rát, phồng rộp, đau nhức sau khi tiếp xúc nhiệt'),
(33, 'đau, sưng, bầm tím ở khớp (cổ chân, cổ tay) sau chấn thương'),
(34, 'khó đi cầu (dưới 3 lần/tuần), phân cứng, đau bụng dưới'),
(35, 'lo lắng quá mức, bồn chồn, tim đập nhanh, khó ngủ'),
(36, 'ngứa da, da có vảy, nổi mẩn hình tròn'),
(37, 'đau nhức răng, nướu sưng, nhạy cảm với nóng/lạnh'),
(38, 'tê, ngứa ran ở ngón cái, ngón trỏ, ngón giữa'),
(39, 'mụn mủ, mụn bọc, mụn đầu đen ở mặt, lưng'),
(40, 'đau khớp khi vận động, cứng khớp (gối, háng)'),
(41, 'nổi mề đay, ngứa, sưng môi, khó thở sau khi ăn'),
(42, 'đau họng, khó nuốt, có mảng trắng trong họng'),
(43, 'mệt mỏi cực độ, sốt, đau họng, sưng hạch'),
(44, 'đau mắt, mờ mắt, thấy quầng sáng quanh đèn'),
(45, 'da đỏ, ngứa, tróc vảy bạc'),
(46, 'mệt mỏi, sút cân, ho dai dẳng, sốt về chiều'),
(47, 'đau ngực, khó thở khi gắng sức, phù chân'),
(48, 'nhìn mờ, thấy ruồi bay, chói mắt'),
(49, 'run tay khi nghỉ, đi chậm chạp, cứng cơ'),
(50, 'đau bụng dữ dội, nôn, bí trung đại tiện'),
(51, 'sốt, đau khớp, ban hình cánh bướm ở mặt'),
(52, 'ngứa hậu môn, đặc biệt là vào ban đêm'),
(53, 'ngứa da, mụn nước ở kẽ ngón tay, ngón chân'),
(54, 'chảy máu cam thường xuyên'),
(55, 'chảy máu chân răng khi đánh răng, hôi miệng'),
(56, 'sốt, rét run, vã mồ hôi (theo cơn)'),
(57, 'yếu cơ, sụp mi mắt, mệt mỏi tăng về chiều'),
(58, 'dễ bầm tím, chảy máu kéo dài khi đứt tay'),
(59, 'đau cơ, cứng cơ, sốt sau khi bị thương (vết thương hở)'),
(60, 'đau rát khi đi tiểu, nước tiểu có mủ, sốt'),
(61, 'đau họng, lưỡi dâu tây, phát ban đỏ mịn toàn thân'),
(62, 'mệt mỏi, da vàng, lách to, nước tiểu sẫm màu'),
(63, 'môi khô, mắt trũng, khóc không có nước mắt (ở trẻ em)'),
(64, 'đau bụng, tiêu chảy, phân nhầy máu'),
(65, 'run tay, tim đập nhanh, sụt cân không rõ nguyên nhân, lồi mắt'),
(66, 'mệt mỏi, tăng cân, sợ lạnh, da khô, rụng tóc'),
(67, 'hay quên, lẫn lộn, khó nhận ra người thân (ở người lớn tuổi)'),
(68, 'giảm thị lực, mờ mắt, đau mắt'),
(69, 'đau bụng dữ dội, nôn ra máu, đi cầu phân đen'),
(70, 'tiểu nhiều, tiểu đêm, tiểu khó, tiểu không hết'),
(71, 'đau bụng dữ dội sau bữa ăn thịnh soạn, nôn nhiều, sốt'),
(72, 'đau hạ sườn phải, sốt, vàng da'),
(73, 'tiêu chảy kéo dài, đau bụng, sụt cân'),
(74, 'yếu một bên mặt, méo miệng, mắt nhắm không kín'),
(75, 'đau lưng lan xuống mông, đùi, cẳng chân'),
(76, 'biến dạng xương, sưng đau, không thể cử động (sau va đập)'),
(77, 'móng tay/chân dày, ố vàng, mủn, có mùi hôi'),
(78, 'mụn nước nhỏ ở môi, mép'),
(79, 'sút cân, ho ra máu, mệt mỏi, nổi hạch'),
(80, 'phát hiện khối u ở vú, thay đổi da vú, tụt núm vú'),
(81, 'chán ăn, sụt cân, đau bụng vùng gan, vàng da'),
(82, 'đau bụng âm ỉ, sụt cân, nôn ra máu, đi cầu phân đen'),
(83, 'rối loạn đại tiện (táo bón, tiêu chảy xen kẽ), phân có máu'),
(84, 'mệt mỏi, phù, tiểu ít, chán ăn'),
(85, 'phù toàn thân, tiểu có bọt, cao huyết áp'),
(86, 'uống rất nhiều (hàng chục lít/ngày), tiểu rất nhiều'),
(87, 'yếu cơ, tê bì chân tay, giảm thị lực, mất thăng bằng'),
(88, 'tê bì, yếu liệt nửa người, méo miệng, nói khó (xảy ra đột ngột)'),
(89, 'đau đầu dữ dội, nôn vọt, cứng gáy, sợ ánh sáng, sốt cao'),
(90, 'đau nhức, mỏi mắt, khô mắt, nhìn mờ khi dùng máy tính'),
(91, 'ngứa dữ dội, nổi mẩn đỏ ở vùng sinh dục'),
(92, 'đau, buốt, nhức răng'),
(93, 'nổi hạch ở cổ, nách, bẹn không đau, sốt, sụt cân'),
(94, 'mệt mỏi, da xanh, dễ chảy máu, sốt, nhiễm trùng thường xuyên'),
(95, 'mụn nước ở bộ phận sinh dục, đau rát'),
(96, 'sùi, u nhú ở bộ phận sinh dục'),
(97, 'loét ở bộ phận sinh dục (không đau)'),
(98, 'sốt, nổi hạch, mệt mỏi (sau khi có hành vi nguy cơ)'),
(99, 'đau bụng kinh dữ dội, đau khi quan hệ, rong kinh'),
(100, 'tim đập nhanh, khó thở, run rẩy, cảm giác sắp chết (xảy ra đột ngột)'),
(101, 'suy nghĩ ám ảnh lặp đi lặp lại, hành vi cưỡng chế (rửa tay, kiểm tra)'),
(102, 'giai đoạn hưng cảm (nói nhiều, ít ngủ) xen kẽ giai đoạn trầm cảm'),
(103, 'co giật, mất ý thức, sùi bọt mép'),
(104, 'đau mỏi cơ bắp lan tỏa, mệt mỏi, khó ngủ, nhiều điểm đau'),
(105, 'vàng da, bụng chướng, dễ bầm tím, mệt mỏi (thường ở người uống rượu bia)'),
(106, 'kinh nguyệt không đều, rậm lông, mụn, tăng cân'),
(107, 'đau bụng dưới (nữ), khí hư bất thường, sốt, đau khi quan hệ'),
(108, 'ho ông ổng (tiếng chó sủa), khó thở về đêm (ở trẻ em)'),
(109, 'da nóng và khô, không ra mồ hôi, lú lẫn, nhiệt độ > 40°C'),
(110, 'run rẩy dữ dội, da lạnh, nói lắp, lú lẫn (sau khi bị lạnh)'),
(111, 'ngứa, sưng môi/mắt, khó thở, tụt huyết áp (sau khi ăn/tiêm thuốc)'),
(112, 'đau bụng, tiêu chảy, sụt cân sau khi ăn (lúa mì, lúa mạch)'),
(113, 'da mặt đỏ bừng (đặc biệt là mũi, má), mụn nhỏ li ti'),
(114, 'ngón tay/chân trắng bệch, tím tái khi gặp lạnh'),
(115, 'khó ngủ, ngủ không sâu, thức dậy vẫn mệt mỏi'),
(116, 'tiểu buốt, tiểu rắt, tiểu lắt nhắt, đau bụng dưới'),
(117, 'da đầu nhờn, gàu, vảy vàng, ngứa'),
(118, 'mệt mỏi, chán ăn, vàng da (có thể không triệu chứng)'),
(119, 'mệt mỏi, chán ăn, vàng da, nước tiểu sẫm màu (có thể không triệu chứng)'),
(120, 'nhìn mờ khi nhìn gần (người lớn tuổi)'),
(121, 'nhìn mờ khi nhìn xa'),
(122, 'nhìn mờ, hình ảnh méo mó'),
(123, 'đau răng dữ dội, sưng nướu, có mủ'),
(124, 'sốt, sợ nước, sợ gió, co giật (sau khi bị chó/mèo cắn)'),
(125, 'sốt cao, rét run, vàng da, lách to'),
(126, 'ban đỏ hình tròn (giống bia bắn) sau khi bị ve cắn'),
(127, 'đau họng, sốt, nuốt vướng, nổi hạch cổ'),
(128, 'yếu đột ngột nửa người, nói ngọng (diễn ra vài phút rồi hết)'),
(129, 'chân nổi gân xanh, nặng chân, mỏi chân, chuột rút về đêm'),
(130, 'sốt về chiều, ho khan, nổi hạch ở cổ (không phải lao phổi)'),
(131, 'đau lưng, cứng cột sống (đặc biệt là buổi sáng), mệt mỏi'),
(132, 'mảng da mất sắc tố (màu trắng), không ngứa'),
(133, 'rụng tóc thành từng mảng tròn, da đầu nhẵn'),
(134, 'ngứa tai, đau tai, sưng ống tai (thường sau khi bơi)'),
(135, 'mệt mỏi, yếu cơ, sạm da, sụt cân, huyết áp thấp'),
(136, 'nóng rát, đau buốt khi đi tiểu'),
(137, 'ngứa da đầu, có vảy trắng, rụng tóc'),
(138, 'đau xương, mệt mỏi, thiếu máu, suy thận (ở người lớn tuổi)'),
(139, 'ra máu âm đạo bất thường, đau bụng dưới, kinh nguyệt nhiều (ở nữ giới)'),
(140, 'đau bụng, phân lẫn máu, sụt cân không rõ nguyên nhân'),
(141, 'yếu cơ, mệt mỏi, chuột rút, co giật'),
(142, 'tự ti về ngoại hình, ám ảnh bởi khuyết điểm nhỏ'),
(143, 'sưng tinh hoàn, đau, sốt'),
(144, 'run rẩy, vã mồ hôi, đói cồn cào, lú lẫn, tim đập nhanh'),
(145, 'mệt mỏi, vã mồ hôi nhiều, da lạnh, chuột rút (do nóng)'),
(146, 'yếu cơ, nhìn mờ, khó nuốt, sụp mi (sau khi ăn đồ hộp)'),
(147, 'đau ngực dữ dội, khó thở đột ngột (sau chấn thương hoặc tự phát)'),
(148, 'khó thở đột ngột, đau ngực, ho ra máu'),
(149, 'đái rắt, đái buốt, đau vùng lưng, sốt, rét run (nữ)'),
(150, 'sưng, nóng, đỏ, đau dữ dội khớp gối (cấp)'),
(151, 'đau nhức mắt, nhìn mờ, thấy màng che, sợ ánh sáng'),
(152, 'mệt mỏi, da vàng, phân bạc màu, nước tiểu sẫm'),
(153, 'co giật toàn thân (ở trẻ em khi sốt cao)'),
(154, 'vết thương bẩn, sưng nóng, đỏ, đau, chảy mủ'),
(155, 'đau bụng dữ dội, nôn, bụng cứng như gỗ'),
(156, 'sưng đau họng, không thể há miệng, sốt cao'),
(157, 'khàn tiếng kéo dài (trên 2 tuần), nói hụt hơi'),
(158, 'đau thốn gót chân (đặc biệt là bước đi đầu tiên buổi sáng)'),
(159, 'ảo giác, hoang tưởng, rối loạn suy nghĩ, hành vi kỳ lạ'),
(160, 'vết cắn (côn trùng), sưng đỏ, ngứa, đau, phồng rộp'),
(161, 'đau rát lưỡi, mảng trắng trên lưỡi (dễ cạo)'),
(162, 'chảy máu âm đạo giữa kỳ kinh, đau bụng dưới'),
(163, 'yếu cơ, mệt mỏi, không thể vận động (đặc biệt là sau ăn)'),
(164, 'da vàng, mắt vàng (ở trẻ sơ sinh)'),
(165, 'ngáy to, buồn ngủ ban ngày, ngưng thở khi ngủ'),
(166, 'đau đầu dữ dội, đột ngột (như sét đánh), cứng gáy'),
(167, 'khó nuốt, nuốt nghẹn, sụt cân, đau ngực'),
(168, 'tiểu máu, đau lưng, sờ thấy khối u ở bụng'),
(169, 'thay đổi nốt ruồi (to ra, đổi màu, viền không đều, chảy máu)'),
(170, 'sưng hạch cổ, khàn tiếng, khó nuốt, ù tai'),
(171, 'đau khi quan hệ, chảy máu âm đạo bất thường (nữ)'),
(172, 'khó tiểu, tiểu ra máu, đau xương (nam giới lớn tuổi)'),
(173, 'nói lắp, lặp từ, khó phát âm'),
(174, 'đau họng, khó nuốt, có đốm trắng ở amidan'),
(175, 'mệt mỏi, da vàng, nước tiểu sẫm màu, sốt (sau khi du lịch)'),
(176, 'đau bụng, tiêu chảy, sụt cân, phân có mỡ'),
(177, 'chóng mặt, ù tai, giảm thính lực (một bên tai)'),
(178, 'đau lưng, sốt, tiểu buốt, tiểu mủ'),
(179, 'phù mặt, phù chân, tiểu ít, nước tiểu có bọt'),
(180, 'sốt cao, đau đầu, cứng gáy, nôn vọt'),
(181, 'đau bụng, tiêu chảy, phân nhầy máu'),
(182, 'tăng cân nhanh, mặt tròn, rạn da tím'),
(183, 'sốt, ho, khó thở, mệt mỏi (sau khi tiếp xúc gia cầm)'),
(184, 'sốt, đau họng, nổi hạch, mệt mỏi'),
(185, 'da khô, ngứa, nứt nẻ, đặc biệt vào mùa đông'),
(186, 'đau bụng, chướng bụng, táo bón, phân có máu'),
(187, 'nổi mẩn đỏ, ngứa, phồng rộp (sau khi tiếp xúc cây/hóa chất)'),
(188, 'đau họng, sốt, ho, sổ mũi, mệt mỏi'),
(189, 'đau bụng, tiêu chảy, nôn, sốt (sau khi ăn uống)'),
(190, 'đau lưng, tiểu buốt, tiểu máu, sốt'),
(191, 'mệt mỏi, da xanh xao, khó thở khi gắng sức'),
(192, 'đau đầu, sốt, mệt mỏi, đau cơ khớp'),
(193, 'đau họng, sốt, ho khan, mệt mỏi'),
(194, 'mất vị giác, mất khứu giác, sốt, ho'),
(195, 'đau bụng, tiêu chảy, nôn, sốt (sau khi đi du lịch)'),
(196, 'đau đầu, chóng mặt, buồn nôn, mệt mỏi'),
(197, 'đau khớp, sưng khớp, cứng khớp');
INSERT INTO DuaLoiKhuyen(TrieuChung_ID, ChuanDoan, LoiKhuyen) VALUES 
(4, 'Nghi ngờ Viêm phổi', 'Cần đi khám ngay lập tức để chụp X-quang và dùng kháng sinh.'),
(5, 'Nghi ngờ Sốt xuất huyết', 'Đến ngay cơ sở y tế, hạ sốt bằng Paracetamol, không dùng Aspirin.'),
(6, 'Viêm kết mạc (Đau mắt đỏ)', 'Rửa mắt bằng nước muối sinh lý, không dụi mắt và đi khám.'),
(7, 'Ngộ độc thực phẩm', 'Uống oresol bù điện giải, nếu nôn mửa nhiều hoặc có máu phải đi viện ngay.'),
(8, 'Trào ngược dạ dày (GERD)', 'Tránh ăn đồ cay nóng, không nằm ngay sau khi ăn, đi khám nội soi.'),
(9, 'Nghi ngờ Viêm xoang', 'Giữ ấm vùng mũi, rửa mũi bằng nước muối và đi khám tai mũi họng.'),
(10, 'Nghi ngờ Sỏi thận', 'Uống thật nhiều nước, đi siêu âm để kiểm tra kích thước sỏi.'),
(11, 'Nhiễm trùng đường tiết niệu', 'Uống nhiều nước, giữ vệ sinh và đi xét nghiệm nước tiểu.'),
(12, 'Chứng đau nửa đầu (Migraine)', 'Nghỉ ngơi trong phòng tối, yên tĩnh, tránh căng thẳng.'),
(13, 'Nghi ngờ Viêm gan', 'Cần đi xét nghiệm máu (men gan, HBsAg) ngay lập tức.'),
(14, 'Dấu hiệu bệnh Tiểu đường', 'Cần đi xét nghiệm máu (đường huyết lúc đói) ngay.'),
(15, 'Viêm da cơ địa (Eczema)', 'Giữ ẩm da, tránh tiếp xúc với chất gây dị ứng, dùng thuốc bôi theo chỉ định.'),
(16, 'Nghi ngờ Viêm khớp dạng thấp', 'Cần đi khám chuyên khoa cơ xương khớp để được chẩn đoán sớm.'),
(17, 'Nghi ngờ bệnh Zona thần kinh', 'Đi khám da liễu, dùng thuốc kháng virus, giữ da sạch sẽ.'),
(18, 'Cúm A/B', 'Nghỉ ngơi, uống nhiều nước, cách ly, dùng thuốc hạ sốt Paracetamol.'),
(19, 'Tăng huyết áp', 'Cần đo huyết áp ngay, đi khám tim mạch, giảm ăn mặn, thư giãn.'),
(20, 'Hen phế quản', 'Dùng thuốc xịt cắt cơn (nếu có), tránh xa dị nguyên, đi khám hô hấp.'),
(21, 'Viêm tai giữa cấp', 'Đi khám tai mũi họng, dùng kháng sinh theo toa, giữ tai khô.'),
(22, 'Phản ứng dị ứng', 'Uống thuốc kháng histamin, tránh xa tác nhân nghi ngờ (thức ăn, bụi).'),
(23, 'Nghi ngờ bệnh Trĩ', 'Ngâm nước ấm, ăn nhiều chất xơ, đi khám chuyên khoa tiêu hóa.'),
(24, 'Nghi ngờ Viêm ruột thừa cấp', 'Cần nhập viện cấp cứu ngay, không ăn uống, chuẩn bị phẫu thuật.'),
(25, 'Rối loạn giấc ngủ', 'Tập thể dục nhẹ, tránh cafe, trà vào buổi tối, tạo thói quen ngủ đúng giờ.'),
(26, 'Dấu hiệu Trầm cảm', 'Cần gặp chuyên gia tâm lý hoặc bác sĩ tâm thần để được tư vấn.'),
(27, 'Viêm dạ dày', 'Cần nội soi dạ dày, kiêng đồ cay nóng, rượu bia, không ăn quá no.'),
(28, 'Cơn Gout cấp', 'Chườm lạnh, uống thuốc kháng viêm (nếu có), kiêng đạm, hải sản, rượu bia.'),
(29, 'Thoát vị đĩa đệm', 'Nằm nghỉ, tránh mang vác nặng, đi khám chuyên khoa cột sống.'),
(30, 'Rối loạn tiền đình', 'Nằm nghỉ ngơi, tránh thay đổi tư thế đột ngột, hạn chế dùng điện thoại, đi khám thần kinh.'),
(31, 'Cảm lạnh thông thường', 'Nghỉ ngơi, uống nhiều nước ấm, súc họng nước muối, tự khỏi sau 5-7 ngày.'),
(32, 'Bỏng da (cấp độ 1-2)', 'Ngâm vùng bỏng vào nước mát ngay, không chọc vỡ nốt phỏng, bôi kem trị bỏng và che vết thương.'),
(33, 'Bong gân', 'Chườm đá ngay (15-20 phút), băng ép, nghỉ ngơi, nâng cao vùng bị thương (RICE).'),
(34, 'Táo bón', 'Ăn nhiều chất xơ (rau xanh, đu đủ), uống 2 lít nước/ngày, tập thể dục, tránh nhịn đi cầu.'),
(35, 'Rối loạn lo âu', 'Tập hít thở sâu, thiền, giảm caffeine, chia sẻ với người thân và tìm chuyên gia tâm lý.'),
(36, 'Nấm da (hắc lào)', 'Giữ da khô sạch, dùng thuốc bôi kháng nấm, không dùng chung khăn tắm, quần áo.'),
(37, 'Sâu răng hoặc Viêm nướu', 'Súc miệng nước muối ấm, đi khám nha sĩ ngay, dùng thuốc giảm đau tạm thời.'),
(38, 'Hội chứng ống cổ tay', 'Để tay nghỉ ngơi, hạn chế gõ máy tính, đeo nẹp cổ tay khi ngủ, đi khám cơ xương khớp.'),
(39, 'Mụn trứng cá', 'Giữ mặt sạch (rửa 2 lần/ngày), không nặn mụn, dùng thuốc bôi, đi khám da liễu nếu nặng.'),
(40, 'Thoái hóa khớp', 'Giảm cân (nếu thừa cân), tập thể dục nhẹ nhàng (bơi lội, đạp xe), đi khám cơ xương khớp.'),
(41, 'Dị ứng thực phẩm', 'Ngưng ăn ngay lập tức, uống thuốc kháng histamin. Nếu khó thở hoặc sưng họng, phải đi cấp cứu ngay.'),
(42, 'Viêm họng mủ (Viêm amidan)', 'Súc họng nước muối, uống nước ấm, đi khám bác sĩ, có thể cần dùng kháng sinh.'),
(43, 'Nghi ngờ Tăng bạch cầu đơn nhân (Mono)', 'Cần nghỉ ngơi tuyệt đối, uống nhiều nước, đi xét nghiệm máu.'),
(44, 'Nghi ngờ Glocom (Tăng nhãn áp)', 'Cần đi khám chuyên khoa mắt ngay lập tức, đây là trường hợp cấp cứu.'),
(45, 'Bệnh Vảy nến', 'Giữ ẩm da, tránh căng thẳng, đi khám da liễu để dùng thuốc đặc trị.'),
(46, 'Nghi ngờ Lao phổi', 'Cần đi chụp X-quang phổi và xét nghiệm đờm ngay. Bệnh lây qua không khí.'),
(47, 'Nghi ngờ Suy tim', 'Hạn chế ăn mặn, nghỉ ngơi, đi khám chuyên khoa tim mạch ngay lập tức.'),
(48, 'Nghi ngờ Đục thủy tinh thể', 'Đi khám chuyên khoa mắt để đo thị lực và cân nhắc phẫu thuật.'),
(49, 'Nghi ngờ bệnh Parkinson', 'Cần đi khám chuyên khoa nội thần kinh để được chẩn đoán và điều trị.'),
(50, 'Nghi ngờ Tắc ruột', 'Đây là ca cấp cứu ngoại khoa. Cần đến bệnh viện ngay, không ăn uống.'),
(51, 'Nghi ngờ Lupus ban đỏ', 'Đi khám chuyên khoa cơ xương khớp/miễn dịch, cần xét nghiệm máu chuyên sâu.'),
(52, 'Nhiễm giun kim', 'Cần uống thuốc xổ giun cho cả gia đình, vệ sinh giường chiếu, cắt móng tay.'),
(53, 'Bệnh ghẻ', 'Đi khám da liễu, bôi thuốc đặc trị, giặt sạch quần áo chăn màn bằng nước nóng.'),
(54, 'Thành mạch yếu / Rối loạn đông máu', 'Ăn thêm vitamin C, tránh ngoáy mũi. Nếu chảy máu nhiều, cần đi khám huyết học.'),
(55, 'Viêm nha chu (Viêm nướu)', 'Cần đi lấy cao răng định kỳ, vệ sinh răng miệng đúng cách, khám nha sĩ.'),
(56, 'Sốt rét', 'Cần đi xét nghiệm máu (kí sinh trùng sốt rét) ngay, đặc biệt nếu ở vùng rừng núi.'),
(57, 'Nghi ngờ Bệnh nhược cơ', 'Đi khám chuyên khoa nội thần kinh, cần làm các xét nghiệm chẩn đoán điện cơ.'),
(58, 'Rối loạn đông máu (Hemophilia / Xuất huyết giảm tiểu cầu)', 'Cần đi khám huyết học ngay, làm xét nghiệm công thức máu và đông máu.'),
(59, 'Nghi ngờ Uốn ván', 'Cần đến bệnh viện cấp cứu ngay lập tức để tiêm phòng và xử lý vết thương.'),
(60, 'Nhiễm lậu cầu', 'Đi khám chuyên khoa da liễu hoặc nam khoa/phụ khoa, xét nghiệm dịch mủ, dùng kháng sinh đặc hiệu.'),
(61, 'Sốt tinh hồng nhiệt (Scarlet fever)', 'Đi khám bác sĩ ngay, đây là bệnh do liên cầu khuẩn, cần dùng kháng sinh.'),
(62, 'Tan máu (Nghi ngờ Thalassemia / Bệnh lý gan)', 'Đi khám chuyên khoa Huyết học, làm xét nghiệm máu và siêu âm bụng.'),
(63, 'Dấu hiệu mất nước nặng', 'Cần bù nước bằng Oresol ngay. Nếu trẻ lừ đừ, không uống được, phải đưa đi cấp cứu ngay.'),
(64, 'Nghi ngờ Lỵ Amip hoặc Lỵ trực khuẩn', 'Cần đi xét nghiệm phân, giữ vệ sinh ăn uống, dùng thuốc theo chỉ định của bác sĩ.'),
(65, 'Cường giáp (Bệnh Basedow)', 'Đi khám chuyên khoa nội tiết, xét nghiệm hormone tuyến giáp (FT4, TSH).'),
(66, 'Suy giáp', 'Đi khám chuyên khoa nội tiết, xét nghiệm hormone tuyến giáp (FT4, TSH).'),
(67, 'Nghi ngờ Bệnh Alzheimer', 'Cần người nhà đưa đi khám chuyên khoa Lão khoa hoặc Thần kinh để đánh giá.'),
(68, 'Tật khúc xạ (Cận/Viễn/Loạn) hoặc bệnh lý mắt', 'Không tự ý mua thuốc nhỏ mắt. Cần đi khám chuyên khoa mắt để đo thị lực.'),
(69, 'Xuất huyết tiêu hóa', 'Đây là ca cấp cứu. Cần nhịn ăn uống và đến bệnh viện ngay lập tức để nội soi cầm máu.'),
(70, 'Phì đại tuyến tiền liệt (ở nam giới lớn tuổi)', 'Đi khám nam khoa, siêu âm tuyến tiền liệt, xét nghiệm PSA.'),
(71, 'Viêm tụy cấp', 'Nhịn ăn uống hoàn toàn và đi cấp cứu ngay lập tức.'),
(72, 'Sỏi mật / Viêm túi mật', 'Đi siêu âm bụng, khám chuyên khoa tiêu hóa.'),
(73, 'Bệnh Crohn / Viêm loét đại tràng', 'Cần đi nội soi đại tràng để chẩn đoán, khám chuyên khoa tiêu hóa.'),
(74, 'Liệt dây thần kinh VII ngoại biên (Liệt Bell)', 'Đi khám thần kinh, châm cứu, vật lý trị liệu, giữ ấm mặt.'),
(75, 'Đau thần kinh tọa', 'Nằm nghỉ, chườm ấm, dùng thuốc giảm đau, đi khám cột sống.'),
(76, 'Gãy xương', 'Cố định tạm thời, không nắn chỉnh, đến bệnh viện để chụp X-quang.'),
(77, 'Nấm móng', 'Đi khám da liễu, dùng thuốc bôi hoặc thuốc uống kháng nấm (cần theo dõi chức năng gan).'),
(78, 'Mụn rộp (Herpes simplex)', 'Bôi thuốc kháng virus (Acyclovir) ngay khi mới có dấu hiệu, tránh hôn hoặc dùng chung đồ.'),
(79, 'Nghi ngờ Ung thư phổi', 'Đi chụp CT-scan phổi, nội soi phế quản, khám chuyên khoa ung bướu.'),
(80, 'Nghi ngờ Ung thư vú', 'Đi siêu âm tuyến vú, chụp nhũ ảnh, khám chuyên khoa sản/ung bướu.'),
(81, 'Nghi ngờ Ung thư gan', 'Đi siêu âm bụng, xét nghiệm máu (AFP), khám chuyên khoa tiêu hóa.'),
(82, 'Nghi ngờ Ung thư dạ dày', 'Cần nội soi dạ dày sinh thiết, khám chuyên khoa tiêu hóa/ung bướu.'),
(83, 'Nghi ngờ Ung thư đại tràng', 'Cần nội soi đại tràng sinh thiết, khám chuyên khoa tiêu hóa/ung bướu.'),
(84, 'Nghi ngờ Suy thận mạn', 'Đi xét nghiệm máu (Creatinin, Ure), xét nghiệm nước tiểu, siêu âm thận.'),
(85, 'Nghi ngờ Viêm cầu thận', 'Đi xét nghiệm nước tiểu (Protein niệu), xét nghiệm máu, khám chuyên khoa thận.'),
(86, 'Nghi ngờ Đái tháo nhạt', 'Đi khám chuyên khoa nội tiết, xét nghiệm nước tiểu và máu.'),
(87, 'Nghi ngờ Xơ cứng rải rác (MS)', 'Đi khám chuyên khoa nội thần kinh, chụp MRI não và tủy sống.'),
(88, 'Đột quỵ não', 'Gọi cấp cứu 115 ngay lập tức, ghi nhớ thời gian khởi phát.'),
(89, 'Viêm màng não', 'Đi cấp cứu ngay lập tức, cần chọc dịch não tủy để chẩn đoán.'),
(90, 'Hội chứng thị giác màn hình (CVS)', 'Áp dụng quy tắc 20-20-20 (mỗi 20 phút, nhìn xa 20 feet, trong 20 giây), dùng nước mắt nhân tạo.'),
(91, 'Nấm bẹn', 'Giữ vùng bẹn khô thoáng, mặc đồ lót cotton, bôi thuốc kháng nấm.'),
(92, 'Viêm tủy răng', 'Đi khám nha sĩ ngay để điều trị tủy, không tự ý uống kháng sinh.'),
(93, 'Nghi ngờ Ung thư hạch (Lymphoma)', 'Đi khám huyết học hoặc ung bướu, cần sinh thiết hạch.'),
(94, 'Nghi ngờ Bệnh bạch cầu (Leukemia)', 'Đi xét nghiệm công thức máu (huyết đồ) ngay.'),
(95, 'Mụn rộp sinh dục (Herpes)', 'Đi khám da liễu, dùng thuốc kháng virus, kiêng quan hệ tình dục.'),
(96, 'Sùi mào gà', 'Đi khám da liễu, đốt laser hoặc áp lạnh, xét nghiệm HPV.'),
(97, 'Nghi ngờ Giang mai', 'Đi khám da liễu, xét nghiệm máu (RPR, TPHA), dùng kháng sinh đặc hiệu.'),
(98, 'Nghi ngờ nhiễm HIV giai đoạn sớm', 'Cần tư vấn và xét nghiệm HIV sau 3 tháng có hành vi nguy cơ.'),
(99, 'Lạc nội mạc tử cung (ở nữ giới)', 'Đi khám phụ khoa, siêu âm, có thể cần dùng thuốc nội tiết hoặc phẫu thuật.'),
(100, 'Cơn hoảng loạn (Panic Attack)', 'Hít thở sâu bằng bụng, trấn an bản thân, tìm nơi yên tĩnh, đi khám tâm lý nếu lặp lại.'),
(101, 'Rối loạn ám ảnh cưỡng chế (OCD)', 'Cần trị liệu tâm lý nhận thức-hành vi (CBT), không tự ý ngăn cản hành vi.'),
(102, 'Rối loạn lưỡng cực', 'Cần bác sĩ tâm thần chẩn đoán, dùng thuốc điều chỉnh khí sắc theo toa.'),
(103, 'Động kinh', 'Để bệnh nhân nằm nghiêng, tránh vật cản, không nhét gì vào miệng. Gọi cấp cứu.'),
(104, 'Đau xơ cơ (Fibromyalgia)', 'Tập thể dục nhẹ nhàng (yoga, đi bộ), vật lý trị liệu, dùng thuốc giảm đau theo chỉ định.'),
(105, 'Xơ gan', 'Kiêng rượu bia tuyệt đối, ăn nhạt, đi khám tiêu hóa gan mật định kỳ.'),
(106, 'Hội chứng buồng trứng đa nang (PCOS)', 'Khám phụ khoa/nội tiết, thay đổi lối sống (ăn uống lành mạnh, giảm cân).'),
(107, 'Viêm vùng chậu (PID)', 'Khám phụ khoa ngay, cần dùng kháng sinh mạnh theo toa, kiêng quan hệ.'),
(108, 'Viêm thanh quản cấp (Croup)', 'Cho trẻ thở không khí ẩm (phòng tắm hơi nước), giữ ấm, nếu khó thở nhiều phải đi viện.'),
(109, 'Say nắng (Sốc nhiệt)', 'Gọi cấp cứu 115 ngay. Đưa vào bóng râm, cởi bớt quần áo, làm mát bằng khăn ướt.'),
(110, 'Hạ thân nhiệt', 'Đưa vào nơi ấm, thay quần áo khô, ủ ấm bằng chăn, cho uống nước ấm (nếu tỉnh táo).'),
(111, 'Sốc phản vệ', 'Gọi cấp cứu 115 ngay. Tiêm Adrenaline (EpiPen) nếu có. Đặt nằm ngửa, gác chân cao.'),
(112, 'Bệnh Celiac (Không dung nạp Gluten)', 'Ngưng ăn mọi thực phẩm chứa gluten (lúa mì, bánh mì, ...), đi khám tiêu hóa.'),
(113, 'Bệnh Rosacea (chứng đỏ mặt)', 'Tránh nắng, rượu bia, đồ ăn cay nóng. Đi khám da liễu để bôi thuốc.'),
(114, 'Hội chứng Raynaud', 'Giữ ấm tay chân (đeo găng tay), bỏ thuốc lá, giảm stress, đi khám cơ xương khớp.'),
(115, 'Mất ngủ kinh niên', 'Vệ sinh giấc ngủ: ngủ đúng giờ, tránh caffeine, điện thoại. Đi khám bác sĩ nếu kéo dài.'),
(116, 'Viêm bàng quang', 'Uống thật nhiều nước, đi khám để xét nghiệm nước tiểu và dùng kháng sinh.'),
(117, 'Viêm da tiết bã (Viêm da dầu)', 'Gội đầu bằng dầu gội trị gàu (chứa Ketoconazole, Selenium Sulfide), đi khám da liễu.'),
(118, 'Nghi ngờ Viêm gan C', 'Cần xét nghiệm máu (anti-HCV) để kiểm tra, bệnh lây qua đường máu.'),
(119, 'Nghi ngờ Viêm gan B', 'Cần xét nghiệm máu (HBsAg) để kiểm tra, bệnh lây qua đường máu và tình dục.'),
(120, 'Lão thị', 'Đi khám mắt để đo thị lực và cắt kính lão (kính đọc sách).'),
(121, 'Cận thị', 'Đi khám mắt để đo thị lực và cắt kính cận.'),
(122, 'Loạn thị', 'Đi khám mắt để đo thị lực và cắt kính loạn thị.'),
(123, 'Áp-xe răng', 'Đi khám nha sĩ ngay, cần chụp X-quang, rạch mủ và dùng kháng sinh.'),
(124, 'Nghi ngờ Bệnh dại', 'Đây là cấp cứu. Đến trung tâm y tế dự phòng tiêm vắc-xin dại và huyết thanh ngay lập tức.'),
(125, 'Sốt vàng da', 'Đi khám bệnh truyền nhiễm, cần nhập viện để theo dõi, điều trị triệu chứng.'),
(126, 'Bệnh Lyme', 'Đi khám bác sĩ, cần dùng kháng sinh kéo dài. Ghi nhớ việc bị ve cắn.'),
(127, 'Viêm họng hạt mạn tính', 'Súc họng nước muối hàng ngày, tránh đồ lạnh, đi khám tai mũi họng.'),
(128, 'Cơn thiếu máu não thoáng qua (TIA)', 'Đi cấp cứu ngay, đây là dấu hiệu cảnh báo đột quỵ sắp xảy ra. Cần chụp MRI/CT não.'),
(129, 'Suy giãn tĩnh mạch chân', 'Tránh đứng hoặc ngồi lâu, mang vớ y khoa, gác chân cao khi ngủ, đi khám tim mạch.'),
(130, 'Lao hạch', 'Đi khám bác sĩ, cần sinh thiết hạch và dùng thuốc kháng lao đủ phác đồ.'),
(131, 'Viêm cột sống dính khớp', 'Đi khám cơ xương khớp, tập vật lý trị liệu, dùng thuốc kháng viêm.'),
(132, 'Bệnh bạch biến', 'Đi khám da liễu, có thể dùng thuốc bôi hoặc liệu pháp ánh sáng, bảo vệ da khỏi nắng.'),
(133, 'Rụng tóc từng mảng', 'Đi khám da liễu, có thể tiêm corticosteroid tại chỗ hoặc bôi thuốc.'),
(134, 'Viêm tai ngoài', 'Giữ tai khô tuyệt đối, đi khám tai mũi họng để làm sạch và nhỏ thuốc kháng sinh.'),
(135, 'Nghi ngờ Bệnh Addison', 'Đi khám chuyên khoa nội tiết, cần xét nghiệm hormone và điện giải đồ.'),
(136, 'Viêm niệu đạo', 'Uống nhiều nước, đi khám tiết niệu hoặc nam khoa/phụ khoa, xét nghiệm nước tiểu.'),
(137, 'Nấm da đầu', 'Dùng dầu gội kháng nấm, đi khám da liễu, có thể cần thuốc uống.'),
(138, 'Nghi ngờ Đa u tủy xương', 'Đi khám chuyên khoa huyết học, cần làm điện di protein huyết thanh, tủy đồ.'),
(139, 'U xơ tử cung / Bệnh lý phụ khoa', 'Đi khám phụ khoa, siêu âm tử cung phần phụ để chẩn đoán chính xác.'),
(140, 'Viêm ruột / Khối u đường tiêu hóa', 'Cần đi nội soi đại tràng ngay lập tức để tìm nguyên nhân.'),
(141, 'Rối loạn điện giải (Hạ Canxi / Kali)', 'Đi khám bác sĩ, xét nghiệm điện giải đồ (Ion đồ) để bù trừ kịp thời.'),
(142, 'Rối loạn mặc cảm ngoại hình (BDD)', 'Cần trị liệu tâm lý, học cách chấp nhận bản thân, tránh phẫu thuật thẩm mỹ không cần thiết.'),
(143, 'Viêm tinh hoàn', 'Nằm nghỉ, nâng cao bìu, chườm lạnh, đi khám nam khoa ngay.'),
(144, 'Tụt đường huyết (Hạ đường huyết)', 'Ăn kẹo, uống nước đường hoặc sữa ngay lập tức. Nếu lơ mơ, gọi cấp cứu.'),
(145, 'Kiệt sức do nóng', 'Di chuyển vào nơi mát, uống nước điện giải (oresol), nghỉ ngơi.'),
(146, 'Nghi ngờ ngộ độc Botulism', 'Cấp cứu 115 ngay lập tức, đây là ngộ độc thần kinh nguy hiểm, cần huyết thanh kháng độc.'),
(147, 'Nghi ngờ Tràn khí màng phổi', 'Gọi cấp cứu 115, không di chuyển, giữ tư thế ngồi thoải mái nhất để thở.'),
(148, 'Nghi ngờ Thuyên tắc phổi (Tắc mạch phổi)', 'Cấp cứu 115 ngay lập tức, đây là tình trạng nguy hiểm tính mạng.'),
(149, 'Viêm thận - bể thận cấp', 'Cần đi khám ngay, xét nghiệm nước tiểu, siêu âm thận, dùng kháng sinh mạnh.'),
(150, 'Viêm khớp nhiễm khuẩn (Viêm mủ khớp)', 'Đi khám cơ xương khớp cấp cứu, cần chọc hút dịch khớp, dùng kháng sinh tĩnh mạch.'),
(151, 'Viêm màng bồ đào', 'Đi khám chuyên khoa mắt ngay, không tự ý nhỏ thuốc, cần điều trị chống viêm đặc hiệu.'),
(152, 'Tắc mật', 'Đi khám tiêu hóa gan mật, siêu âm bụng, cần can thiệp giải quyết tắc nghẽn.'),
(153, 'Sốt cao co giật (lành tính ở trẻ em)', 'Hạ sốt (paracetamol), lau mát, để trẻ nằm nghiêng. Cần đi khám để loại trừ viêm màng não.'),
(154, 'Vết thương nhiễm trùng', 'Cần rửa sạch vết thương bằng nước muối sinh lý, đi khám để bác sĩ kê kháng sinh.'),
(155, 'Viêm phúc mạc (Thủng tạng rỗng)', 'Cấp cứu ngoại khoa khẩn cấp, cần phẫu thuật ngay.'),
(156, 'Áp-xe quanh Amidan', 'Đi khám tai mũi họng ngay, cần rạch dẫn lưu mủ và dùng kháng sinh.'),
(157, 'Viêm thanh quản mạn / Hạt xơ dây thanh', 'Hạn chế nói, đi khám tai mũi họng để nội soi thanh quản.'),
(158, 'Viêm cân gan chân', 'Giãn cơ (căng gót chân), đi giày đế mềm, chườm lạnh, vật lý trị liệu.'),
(159, 'Rối loạn tâm thần (Nghi ngờ Tâm thần phân liệt)', 'Cần đưa đến bác sĩ tâm thần, không để bệnh nhân một mình, giữ an toàn.'),
(160, 'Côn trùng cắn (Phản ứng tại chỗ)', 'Rửa sạch vết cắn, chườm lạnh, bôi thuốc chống ngứa. Nếu khó thở, phải đi cấp cứu (sốc phản vệ).'),
(161, 'Nấm miệng (Nấm Candida)', 'Đi khám bác sĩ hoặc nha sĩ, dùng thuốc kháng nấm rơ miệng (Nystatin).'),
(162, 'Rối loạn kinh nguyệt / Chảy máu cơ năng', 'Đi khám phụ khoa để siêu âm, loại trừ nguyên nhân thực thể (u, polyp).'),
(163, 'Liệt chu kỳ (Hạ Kali máu)', 'Đi cấp cứu ngay, cần xét nghiệm điện giải đồ và bù Kali tĩnh mạch.'),
(164, 'Vàng da sơ sinh', 'Cho trẻ tắm nắng (trước 8h sáng), nếu vàng da nhiều cần đi khám nhi (chiếu đèn).'),
(165, 'Ngưng thở khi ngủ do tắc nghẽn (OSA)', 'Đi khám hô hấp hoặc trung tâm rối loạn giấc ngủ (đo đa ký giấc ngủ), giảm cân.'),
(166, 'Xuất huyết dưới nhện (Chảy máu não)', 'Cấp cứu 115 ngay lập tức, đây là đột quỵ xuất huyết não, cần chụp CT não khẩn.'),
(167, 'Nghi ngờ Ung thư thực quản', 'Đi nội soi thực quản - dạ dày ngay lập lức, cần sinh thiết.'),
(168, 'Nghi ngờ Ung thư thận', 'Đi siêu âm bụng, chụp CT bụng, khám chuyên khoa tiết niệu.'),
(169, 'Nghi ngờ Ung thư da (Melanoma)', 'Đi khám da liễu ngay, cần sinh thiết nốt ruồi để chẩn đoán.'),
(170, 'Nghi ngờ Ung thư vòm họng', 'Đi nội soi tai mũi họng, sinh thiết vòm họng, khám ung bướu.'),
(171, 'Viêm cổ tử cung / Ung thư cổ tử cung', 'Đi khám phụ khoa ngay, làm xét nghiệm Pap smear và soi cổ tử cung.'),
(172, 'Nghi ngờ Ung thư tuyến tiền liệt', 'Đi khám nam khoa, siêu âm, xét nghiệm máu (PSA), sinh thiết tuyến tiền liệt.'),
(173, 'Rối loạn giao tiếp (Nói lắp)', 'Cần đi khám chuyên gia ngôn ngữ trị liệu, luyện tập hít thở, giảm căng thẳng.'),
(174, 'Viêm amidan hốc mủ', 'Súc họng nước muối ấm, đi khám tai mũi họng, có thể cần cắt amidan nếu tái phát nhiều.'),
(175, 'Nghi ngờ Viêm gan A', 'Đi xét nghiệm máu (anti-HAV), nghỉ ngơi, ăn uống hợp vệ sinh, bệnh lây qua đường tiêu hóa.'),
(176, 'Hội chứng kém hấp thu', 'Đi khám tiêu hóa, nội soi, xét nghiệm phân, cần điều trị nguyên nhân và bổ sung dinh dưỡng.'),
(177, 'Nghi ngờ U dây thần kinh số 8', 'Đi khám tai mũi họng/thần kinh, chụp MRI não có cản từ.'),
(178, 'Viêm đài bể thận', 'Cần nhập viện, dùng kháng sinh tĩnh mạch, siêu âm hệ tiết niệu.'),
(179, 'Hội chứng thận hư', 'Đi khám chuyên khoa thận, xét nghiệm protein niệu 24h, sinh thiết thận.'),
(180, 'Nghi ngờ Viêm màng não mủ', 'Cấp cứu 115 ngay. Cần chọc dịch não tủy, dùng kháng sinh tĩnh mạch khẩn cấp.'),
(181, 'Hội chứng lỵ', 'Xét nghiệm phân, uống nhiều nước, bù điện giải, có thể cần kháng sinh.'),
(182, 'Hội chứng Cushing', 'Đi khám nội tiết, xét nghiệm cortisol máu, tìm nguyên nhân (u tuyến yên, thượng thận).'),
(183, 'Nghi ngờ Cúm gia cầm (H5N1, H7N9)', 'Đến bệnh viện ngay, cách ly, thông báo lịch sử tiếp xúc gia cầm, dùng thuốc kháng virus.'),
(184, 'Tăng bạch cầu đơn nhân (Bệnh Mono)', 'Nghỉ ngơi, uống nhiều nước, hạ sốt, tránh vận động mạnh (nguy cơ vỡ lách).'),
(185, 'Da khô (Xerosis)', 'Dùng kem dưỡng ẩm thường xuyên, uống đủ nước, không tắm nước quá nóng.'),
(186, 'Viêm túi thừa / Polyp đại tràng', 'Đi nội soi đại tràng, ăn nhiều chất xơ, uống đủ nước.'),
(187, 'Viêm da tiếp xúc dị ứng', 'Rửa sạch vùng tiếp xúc, tránh gãi, bôi kem chứa corticoid, uống thuốc kháng histamin.'),
(188, 'Viêm họng cấp', 'Súc họng nước muối ấm, uống nhiều nước, nghỉ ngơi, hạ sốt nếu cần.'),
(189, 'Viêm dạ dày ruột cấp (do virus/vi khuẩn)', 'Bù nước (Oresol), ăn nhẹ (cháo), nghỉ ngơi. Nếu sốt cao, phân có máu phải đi khám.'),
(190, 'Nhiễm trùng tiết niệu (cao)', 'Đi khám bác sĩ, xét nghiệm nước tiểu, siêu âm thận, dùng kháng sinh.'),
(191, 'Thiếu máu', 'Đi xét nghiệm công thức máu, tìm nguyên nhân (thiếu sắt, tan máu...), bổ sung sắt/B12.'),
(192, 'Sốt siêu vi', 'Nghỉ ngơi, uống nhiều nước, hạ sốt, theo dõi các triệu chứng khác.'),
(193, 'Viêm họng / Cảm cúm', 'Nghỉ ngơi, súc họng, uống nước ấm, theo dõi thêm các triệu chứng khác.'),
(194, 'Nghi ngờ COVID-19', 'Tự cách ly, test nhanh/PCR, báo y tế địa phương, theo dõi triệu chứng.'),
(195, 'Tiêu chảy du lịch', 'Bù oresol, ăn uống cẩn thận, dùng thuốc cầm tiêu chảy (Loperamid) nếu cần.'),
(196, 'Rối loạn tiền đình / Thiếu máu não', 'Nằm nghỉ, tránh thay đổi tư thế đột ngột, đi khám thần kinh.'),
(197, 'Viêm khớp / Thoái hóa khớp', 'Nghỉ ngơi, chườm ấm, dùng thuốc giảm đau (Paracetamol), đi khám cơ xương khớp.');