/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo_Test;

import baitapaes.*;
import demo.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;



public class frm_ChuanDoan extends javax.swing.JFrame {

    private static final String DB_URL = "jdbc:mysql://localhost:3306/FILEBENH?useSSL=false&serverTimezone=UTC";
    private static final String DB_USER = "root";
    private static final String DB_PASSWORD = "134679"; // <-- THAY MẬT KHẨU CỦA BẠN VÀO ĐÂY
    
    public frm_ChuanDoan() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_trieuchung = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_chuadoan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_ketqua = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Hệ Thống Chẩn Đoán Bệnh");

        txt_trieuchung.setColumns(20);
        txt_trieuchung.setRows(5);
        jScrollPane1.setViewportView(txt_trieuchung);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mời bạn nhập triệu chứng bệnh:");

        btn_chuadoan.setBackground(new java.awt.Color(102, 204, 255));
        btn_chuadoan.setText("Chẩn đoán");
        btn_chuadoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chuadoanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kết quả chẩn đoán:");

        txt_ketqua.setColumns(20);
        txt_ketqua.setRows(5);
        jScrollPane2.setViewportView(txt_ketqua);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btn_chuadoan, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_chuadoan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chuadoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chuadoanActionPerformed
        String userInput = txt_trieuchung.getText();
        if (userInput == null || userInput.trim().isEmpty()) {
            txt_ketqua.setText("Vui lòng nhập triệu chứng.");
            return;
        } // <-- LỖI DẤU } THỪA ĐÃ ĐƯỢC XÓA Ở ĐÂY

       txt_ketqua.setText("Đang phân tích...");
        Set<String> userSymptoms = new HashSet<>(Arrays.asList(userInput.toLowerCase().split("\\s*,\\s*")));

        // --- LOGIC MỚI: Tạo 2 danh sách kết quả ---
        StringBuilder ketQuaChinhXac = new StringBuilder(); // Ưu tiên 1: Khớp 100%
        int soBenhChinhXac = 0;
        
        StringBuilder ketQuaCoThe = new StringBuilder(); // Ưu tiên 2: Khớp 1 phần
        int soBenhCoThe = 0;

        String sql = "SELECT ttc.TrieuChung, dlk.ChuanDoan, dlk.LoiKhuyen "
                + "FROM TenTrieuChung AS ttc "
                + "JOIN DuaLoiKhuyen AS dlk ON ttc.ID = dlk.TrieuChung_ID";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            txt_ketqua.setText("Lỗi: Không tìm thấy MySQL JDBC Driver.\nHãy kiểm tra thư viện (Libraries) của project.");
            return;
        }

        try (java.sql.Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD); 
             PreparedStatement pstmt = conn.prepareStatement(sql); 
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                Set<String> dbSymptoms = new HashSet<>(Arrays.asList(rs.getString("TrieuChung").toLowerCase().split("\\s*,\\s*")));
                Set<String> intersection = new HashSet<>(userSymptoms);
                intersection.retainAll(dbSymptoms);
                int matchCount = intersection.size();

                String chuanDoan = rs.getString("ChuanDoan");
                String loiKhuyen = rs.getString("LoiKhuyen");
                if (matchCount > 0 && matchCount == dbSymptoms.size()) {
                    soBenhChinhXac++;
                    ketQuaChinhXac.append("--- BẠN ĐANG CÓ THỂ MẮC PHẢI  ").append(soBenhChinhXac).append(" ---\n");
                    ketQuaChinhXac.append("Chẩn đoán: ").append(chuanDoan).append("\n");
                    ketQuaChinhXac.append("Lời khuyên: ").append(loiKhuyen).append("\n\n");
                } 
                // Cấp 2: Nếu không khớp 100%, kiểm tra xem có khớp 1 phần không
                else if (matchCount > 0) { 
                    soBenhCoThe++;
                    ketQuaCoThe.append("--- BẠN ĐANG CÓ THỂ MẮC PHẢI ").append(soBenhCoThe).append(" ---\n");
                    ketQuaCoThe.append("Chẩn đoán: ").append(chuanDoan).append("\n");
                    ketQuaCoThe.append("Lời khuyên: ").append(loiKhuyen).append("\n\n");
                }
            }

            // --- Hiển thị kết quả tổng hợp lên giao diện ---
            if (soBenhChinhXac > 0) {
                // ƯU TIÊN 1: Nếu có bệnh khớp 100%, chỉ hiển thị chúng
                txt_ketqua.setText(ketQuaChinhXac.toString());
            } else if (soBenhCoThe > 0) {
                // ƯU TIÊN 2: Nếu không có bệnh nào khớp 100%, thì hiển thị các bệnh khớp 1 phần
                txt_ketqua.setText(ketQuaCoThe.toString());
            } else {
                // Không tìm thấy bất kỳ kết quả nào
                String foundAdvice = "Không xác định được bệnh dựa trên các triệu chứng bạn cung cấp. Vui lòng đi khám bác sĩ để biết rõ bệnh tình.";
                txt_ketqua.setText(foundAdvice);
            }

        } catch (Exception e) {
            e.printStackTrace();
            txt_ketqua.setText("Lỗi kết nối hoặc truy vấn CSDL: " + e.getMessage());
        }   
    }//GEN-LAST:event_btn_chuadoanActionPerformed
   

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(frm_ChuanDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(frm_ChuanDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(frm_ChuanDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(frm_ChuanDoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new frm_ChuanDoan().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chuadoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_ketqua;
    private javax.swing.JTextArea txt_trieuchung;
    // End of variables declaration//GEN-END:variables
}
